### ISSUE TITLE
Won't compile on scala 2.11.6

### ISSUE THREAD

**Issue by dowobeha** [jhclark/ducttape#173]
The following errors occur when compiling ducttape with scala 2.11.6:
```
ducttape.git/src/main/scala/ducttape/hyperdag/HyperDag.scala:39: error: in class HyperDag, multiple overloaded alternatives of method unpackedWalker define default arguments.
class HyperDag[V,H,E](val roots: Seq[PackedVertex[V]],
      ^
ducttape.git/src/main/scala/ducttape/hyperdag/meta/MetaHyperDag.scala:32: error: in class MetaHyperDag, multiple overloaded alternatives of method unpackedWalker define default arguments.
class MetaHyperDag[V,M,H,E](val delegate: HyperDag[V,H,E],
      ^
ducttape.git/src/main/scala/ducttape/hyperdag/meta/PhantomMetaHyperDag.scala:43: error: in class PhantomMetaHyperDag, multiple overloaded alternatives of method unpackedWalker define default arguments.
class PhantomMetaHyperDag[V,M,H,E](val delegate: MetaHyperDag[Option[V],M,H,E]) {
```

**Comment by dowobeha** [comment]
This same code does compile on scala 2.10.5

**Comment by jhclark** [comment]
Do you really need to upgrade it right now? Scala releases are somewhat tumultuous.


small device, small sentences





On Tue, Jun 16, 2015 at 2:15 PM -0700, "Lane Schwartz" <notifications@github.com> wrote:
This same code does compile on scala 2.10.5

---

**Comment by dowobeha** [comment]
No, I don't. I just started with the latest when I started on a new machine

On Tuesday, June 16, 2015, Jonathan Clark <notifications@github.com> wrote:

> Do you really need to upgrade it right now? Scala releases are somewhat
> tumultuous.
>
>
> small device, small sentences
>
>
>
>
>
> On Tue, Jun 16, 2015 at 2:15 PM -0700, "Lane Schwartz" <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> This same code does compile on scala 2.10.5
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jhclark/ducttape/issues/173#issuecomment-112571809
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhclark/ducttape/issues/173#issuecomment-112637582>.
>


-- 
When a place gets crowded enough to require ID's, social collapse is not
far away.  It is time to go elsewhere.  The best thing about space travel
is that it made it possible to go elsewhere.
                -- R.A. Heinlein, "Time Enough For Love"
